namespace DynamicXaml.WinUI
{
    [default_interface]
    runtimeclass DynamicLoader
    {
        [static_name("IDynamicLoaderStatics", 8D73FB40-69B1-41E4-8EE7-905C4EEA8FB1)]
        {
            [default_overload]
            static void LoadPri(String priFilePath);
            [method_name("LoadPriWithStorageFile")]
            static void LoadPri(Windows.Storage.StorageFile priFile);

            [default_overload]
            static Boolean TryLoadPri(String priFilePath);
            [method_name("TryLoadPriWithStorageFile")]
            static Boolean TryLoadPri(Windows.Storage.StorageFile priFile);
        }
    }
}
