#include <Common.h>

namespace DynamicXaml.UWP
{
    static runtimeclass DynamicLoader
    {
        [static_name("IDynamicLoaderStatics", 306A8DD6-C919-4D7A-80A7-2CD89B1A43BB)]
        {
            static Boolean EnableUnsafeHooks { get; set; };

            static void LoadPri(Windows.Storage.StorageFile priFile);
        }

        #include <IDynamicLoaderStatics2.inl>
    }
}
